/* eslint-disable tailwindcss/no-custom-classname */
/* eslint-disable @typescript-eslint/restrict-template-expressions */
import { motion, useAnimation } from 'framer-motion';
import Head from 'next/head';
import { useState, useEffect } from 'react';
import { AiFillHome } from 'react-icons/ai';
import {
  BsFillArrowLeftSquareFill,
  BsFillArrowRightSquareFill
} from 'react-icons/bs';
import { FaBookOpen, FaCog } from 'react-icons/fa';
import { GiStairs } from 'react-icons/gi';
import { IoTelescope } from 'react-icons/io5';


const data = [
  {
    name: '',
    items: [
      {
        title: 'ホーム',
        icon: AiFillHome,
      },
      {
        title: '性格分析',
        icon: IoTelescope,
      },
      {
        title: '自己分析',
        icon: FaBookOpen,
      },
      {
        title: '目標設定',
        icon: GiStairs,
      },
    ]
  }
];

const datafooter = [
  {
    name: '',
    items: [
      {
        title: '設定',
        icon: FaCog,
      },
    ]
  }
];

export const SideBar= () => {

  const [active, setActive] = useState(false);
  const controls = useAnimation();
  const controlText = useAnimation();
  const controlTitleText = useAnimation();

  const showMore = () => {
    void controls.start({
      width: '200px',
      transition: { duration: 0.001 }
    });
    void controlText.start({
      opacity: 1,
      display: 'block',
      transition: {delay:0.3}
    });
    void controlTitleText.start({
      opacity: 1,
      transition: {delay:0.3}
    });

    setActive(true);
  };

  const showLess = () => {
    void controls.start({
      width: '62px',
      transition: { duration: 0.001 }
    });

    void controlText.start({
      opacity: 0,
      display: 'none',
    });

    void controlTitleText.start({
      opacity: 0,
    });

    setActive(false);

  };

  useEffect(() => {
    showMore();
  },[]);

  return (
    <div className=' bg-primary' >
      <Head>
        <title>Sidebar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <motion.div animate={controls} className='group flex relative flex-col py-10 max-w-[250px] border-r border-gray-700 duration-300 animate' >

        {/* サイドバーの開閉 */}
        {active && <BsFillArrowLeftSquareFill onClick={showLess} className='hidden group-hover:block absolute top-10 -right-4 text-2xl text-white cursor-pointer' />}
        {!active && <BsFillArrowRightSquareFill onClick={showMore} className='absolute top-10 -right-4 text-2xl text-white cursor-pointer' />}

        <div className='grow'>
          {data.map((group, index) => (
            <div key={index} className='my-2' >
              <motion.p animate={controlTitleText} className='mb-2 ml-4 text-lg font-bold text-gray-500' >{group.name}</motion.p>

              {group.items.map((item, index2) => (
                <div key={index2} className='flex items-center py-2 px-4 hover:text-white hover:bg-gray-400 rounded-3xl hover:rounded-xl transition-all duration-300 ease-linear cursor-pointer'> 
                  <item.icon className='text-3xl text-theme-light' />
                  <motion.span animate={controlText} className='ml-4 font-bold text-theme-light' > {item.title}</motion.span>
                </div>

              ))}
            </div>
          ))}
        </div>
        <div>
          {datafooter.map((group, index) => (
            <div key={index} className='my-2' >
              <motion.p animate={controlTitleText} className='mb-2 ml-4 text-lg font-bold text-gray-500' >{group.name}</motion.p>

              {group.items.map((item, index2) => (
                <div key={index2} className='flex items-center py-2 px-4 hover:text-white hover:bg-gray-400 rounded-3xl hover:rounded-xl transition-all duration-300 ease-linear cursor-pointer' >
                  <item.icon className='text-3xl text-theme-light' />
                  <motion.span animate={controlText} className='ml-4 font-bold text-theme-light' > {item.title}</motion.span>
                </div>

              ))}
            </div>
          ))}
        </div>
      </motion.div>

    </div>
  );
};
